language : android

jdk : oraklejdk7

android:
components:
  - plantform-tools #ADB(디바이 또는 에뮬레이터 통신)
  - tools #실제 안드로이드 SDK
  - build-tools-25.0.1 #빌드툴버전
  - android-25
  - extra-android-m2repository #maden repository와 통합된 라이브러리

before_install:
  - chmod +x gradlew

script : ./gradlew build

